# Generated by Django 2.2.17 on 2021-03-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20210322_1222'),
        ('authnapp', '0007_auto_20210322_1230'),
    ]

    operations = [
    ]
